### ISSUE TITLE
I seem to be crashing upon entering a valve server

### ISSUE THREAD

**Issue by FireWolf700** [ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP#2]
So I preload a map for the main menu, and I just downloaded the new version 3.3.6. Upon loading up and entering a valve server, I get a crash to desktop. No error or anything.

**Comment by kevinvanrijn** [comment]
I'm also preloading a map before play. In case it matters, I do this using the `map_background` command. (I do not disconnect from this map afterwards. Instead I let it automatically disconnect for me once I join a server.)

I would suggest not preloading to avoid crashes though. Unless you have a good reason to. (I believe custom animations on Valve servers was one? If that still works anyways.)

I get occasional crashes joining Valve servers. (Non pure servers are fine, I've not tried community servers with pure settings yet.) These crashes don't seem to be caused by anything specific from the mod itself. It's likely a problem in the code that enforces pure settings. (So that would be on Valve's end.) Some files are seemingly more volatile than others. It's weird.

---

And finally for finding the actual cause of your crashes:

I'm assuming there is nothing wrong with your installation but just to make sure, could you [verify the integrity of your game cache](https://www.youtube.com/watch?v=4PZng5vj9ic) and try joining a server once more after that?

I've also since released a newer version. Available [here](https://github.com/ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP/releases). Updating might fix your issues.

And if that doesn't fix it:

* Please take a picture of your Main Menu. (<kbd>F12</kbd> by default.)
* What does the rest of your [custom folder](https://www.youtube.com/embed/CWlSLH-8pXM?autoplay=1&start=2&end=20) look like? (TF2 tends to crash more with conflicting mods.)
* Have you set any [launch options](https://www.youtube.com/watch?v=ixJrwGGLSN0)?
* In the [cfg folder](https://www.youtube.com/embed/3rOZFxcL_Rs?autoplay=1&start=18&end=27), what are the contents of  `autoexec.cfg` and `config.cfg`? (Please upload to [Pastebin](https://pastebin.com/) or a similar site.)

**Comment by FireWolf700** [comment]
I no longer crash upon entering a Valve server. This was fixed a while ago either by me or an update, no idea which.

However, I cannot seem to get the new textures to show up in the first place.
`//Modding Commands
sv_pure 0
mod_load_anims_async 0
mod_load_mesh_async 0
mod_load_vcollide_async 0
cl_always_flush_models 0
sv_allow_point_servercommand always

map_background preloader`

These are the commands I'm using in order to preload animations and the textures, however I see no difference anywhere, be it in supply cabinets, the wood on the dressing lockers, or even the bottles in spawn.

**Comment by kevinvanrijn** [comment]
Valve servers force pure settings. The mod will be almost completely disabled while you're on them.

The mod supports Valve servers in the sense that it doesn't crash and gets disabled correctly. The  `sv_pure` issues I've been fixing were problems with Valve servers not loading certain models / textures correctly after disabling them.

---

You should be able to tell if the mod is working by looking at the "Odor B Gone" spray in 2Fort spawn. I believe all 4 spawns have a can somewhere.

![mat_picmip](https://user-images.githubusercontent.com/6368561/39804232-c3cda522-5373-11e8-96bf-bba778bef2bb.png)

On Valve servers it should look blurry (mat_picmip 0 or worse) while on community servers (that allow mods) or running the map locally (`map ctf_2fort` in the console) it should look like the mat_picmip -10 version.

---

As for your commands:

`mod_load_anims_async`, `mod_load_mesh_async`, `mod_load_vcollide_async`, and `cl_always_flush_models` are all already 0 by default, so these would do nothing from what I can tell.

`sv_pure` and `sv_allow_point_servercommand` are server side only commands so they would only apply to the preloader map you're running when starting the game and to maps run locally. I'm not sure what the default values for both are since I'm setting them both in my config as well but I don't believe they're necessary either.

---

If that's not it:

* Please take a picture of your Main Menu. (<kbd>F12</kbd> by default.)
* What does the rest of your [custom folder](https://www.youtube.com/embed/CWlSLH-8pXM?autoplay=1&start=2&end=20) look like?
* Have you set any [launch options](https://www.youtube.com/watch?v=ixJrwGGLSN0)?
* In the [cfg folder](https://www.youtube.com/embed/3rOZFxcL_Rs?autoplay=1&start=18&end=27), what are the contents of  `autoexec.cfg` and `config.cfg`? (Please upload to [Pastebin](https://pastebin.com/) or a similar site.)
