### ISSUE TITLE
Some Problems With the New Animations

### ISSUE THREAD

**Issue by FireWolf700** [ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP#5]
At the moment I already have animation overhauls for Spy and Medic, which is probably the reason why the Disguise Kit disappeared as well as the Watch.
For Medic, there is no sound heard from the Medigun, again probably because of the overhauls I already have.

I'd recommend making the animation files optional, simply so that this doesn't happen.

**Comment by kevinvanrijn** [comment]
Make sure to load TIP first and let anything else override it. You can do this by adding a couple of 'Z's to the start of the filename so it's listed last in your file explorer. (Assuming you're sorting on name.) TF2 loads mods in reverse alphabetical order.

That way your animation overhaul can change whatever it wants and nullify the animation changes in TIP. (Animations are stored in a single file per class.)

If that doesn't work, could you share a screenshot of your custom folder?

---

The one thing that might still cause issues is the clicking noise added to the Dead Ringer. Since it has been added to the model instead of the animation you might still get the clicking noise even though your animation is doing something completely different.

I'll see if I can move that sound into the animations itself.

**Comment by kevinvanrijn** [comment]
I decided to release a small mod that nullifies the animation changes before any other mods get loaded. You can find it alongside the release of [3.3.10.fix.1](https://github.com/ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP/releases).

This makes the animation changes opt-out instead of opt-in like you suggested. I prefer keeping them as the default as they only improve upon the base game with zero downsides.

---

That leaves us with the load order of your animation mod. If you added a couple of 'Z's to the base mod you should add the same amount to the nullifier mod to not trip up the load order between the two. Then everything *should* just figure itself out and work.
