### ISSUE TITLE
Crash on join server using sv_pure 2

### ISSUE THREAD

**Issue by steampunko** [ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP#6]
Whenever I join a server using sv_pure 2, it immediately crashes when loaded, mainly Valve servers. I can join community servers fine

**Comment by kevinvanrijn** [comment]
Is your game crashing only sometimes or every time you attempt to join a Valve server?

I personally get crashes every once in a while joining Valve servers. These crashes don't seem to be caused by anything specific from the mod itself. It's likely a problem in the code that enforces pure settings. (So that would be on Valve's end.) Some files are seemingly more volatile than others. It's weird.

---

As for finding the actual cause of your crashes, I'm going to need some additional information.

I'm assuming there is nothing wrong with your installation but just to make sure, could you [verify the integrity of your game cache](https://www.youtube.com/watch?v=4PZng5vj9ic) and try joining a server once more after that?

And if that doesn't fix it:

* Please take a picture of your Main Menu. (<kbd>F12</kbd> by default.)
* What does the rest of your [custom folder](https://www.youtube.com/embed/CWlSLH-8pXM?autoplay=1&start=2&end=20) look like? (TF2 tends to crash with conflicting mods.)
* Have you set any [launch options](https://www.youtube.com/watch?v=ixJrwGGLSN0)?
* In the [cfg folder](https://www.youtube.com/embed/3rOZFxcL_Rs?autoplay=1&start=18&end=27), what are the contents of `autoexec.cfg` (if it exists) and `config.cfg`? (Please upload to [Pastebin](https://pastebin.com/) or a similar site.)

**Comment by steampunko** [comment]
Main Menu (I'm using the HUD called toonhud)
![20180611140611_1](https://user-images.githubusercontent.com/16859299/41257127-a80bca86-6d80-11e8-8c75-cd27a6ad84cf.jpg)

**Custom Folder (workshop folder is empty)**
![custom folder](https://user-images.githubusercontent.com/16859299/41257172-c5fa457c-6d80-11e8-96de-de1d84b83dca.png)

**Launch Options**
-windowed -noborder

**autoexec.cfg**
https://pastebin.com/D51sJZZX

**config.cfg**
https://pastebin.com/fYBFrcCK

**Comment by kevinvanrijn** [comment]
Okay, so looking through everything there is definitely nothing wrong on your end.

Since it crashes only sometimes I believe this is the same bug I mentioned in my previous post. In that case it's a Valve bug and I don't believe any change here would circumvent it, unfortunately.

---

Just to confirm this is the same problem:

* Crashes should occur the moment the loading screen for joining a server is complete or rarely even half a second after joining.
* This happens on every map, but there is no map that crashes every time.

**Comment by steampunko** [comment]
That is correct. If there's nothing I can do about, I probably will be fine. I don't usually play on valve servers anyways!

**Comment by kevinvanrijn** [comment]
Ever since the release of [3.3.11](https://github.com/ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP/releases) my crashes have been severely reduced.

I thought the crashes may have had something to do with the size of the of the mod. Apparently not though.

Maybe the crashing was reduced thanks to a driver update. I don't know. It would make sense since the crash happens once the game starts rendering the world, or rendering the players for the delayed crash. I have no clue what change in the repo could have reduced crashes in any case.

Best I can tell you is to stay updated.

I'm closing this issue for the time being. I don't think there is anything left to do here.
