### ISSUE TITLE
Suggestion for weapon models?

### ISSUE THREAD

**Issue by bassroyt** [ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP#7]
Thanks for all this, really helps me enjoy playing on community servers more with TF2 looking so good. I used to follow T.I.P since its first prerelease many years back, and I'd follow contributions and updates on the Emporiums. But now there are some files that were meant for T.I.P that are lost in the void now because the host download site went down for a lot of mods, making the mods attached to them irretrievable. It doesn't help as well that most of the veteran modders for T.I.P project are no longer on Facepunch, so getting a new download link from original authors was out of the question. Whatever's left for grabs is just the remnants of something that could've exploded in the TF2 modding community. Seeing your update on GitHub really surprised and excited me, and you should definitely try putting this on the Facepunch Emporium. I have one suggestion for this if you plan on updating it. It's Game Zombie's T.I.P World Models. They're the stock weapons and a few other unlockables in higher poly and textures. I've had the vpk for them for years, and I can send them over to you if you'd like to take a look at them and see if it can fit with your mod.

**Comment by kevinvanrijn** [comment]
I'd love to take a look at your file. I'm hoping those models aren't horribly outdated but I can definitely compare everything in-game and see what's usable as is and what needs updating.

I believe GitHub allows you to drag `.zip` files into the comment box. Not sure about other extensions. You're free to upload it wherever you want though.

**Comment by kevinvanrijn** [comment]
After a bit of Googling it seems a lot of Game Zombie's work has already been updated by other people, so I should be able to get everything working fairly quickly. Anything that hasn't been updated (or at least re-uploaded) yet I'd be able to update based on your file.

**Comment by kevinvanrijn** [comment]
Sure, you should be able to send them to -snip-

Edit: removed email

**Comment by kevinvanrijn** [comment]
It has been a while. I've taken a look at the files you sent me and unfortunately I have no way to actually use them. Instead of containing just the fixes it contains all weapons along with all textures. Giving me no good way to figure out what was changed and if those changes still work. I can't tell apart what files are different from the base game because they contain fixes and what files are different because Valve has updated them.

I think it would be best to start over from scratch. First creating a list of weapons that need fixing and then either using known good fixes made by the community or creating them myself.

**Comment by kevinvanrijn** [comment]
I'm closing this issue for now. Further discussion can take place in https://github.com/ModdingTF2/The-closest-thing-to-an-updated-version-of-TF2-TIP/issues/13 .
